language: java
env:
  global:
    - GH_REF: github.com/w3c/wcag.git
    
git:
  depth: 3
  
before_install:
  - tar -xzvf lib/apache-ant-1.10.6-bin.tar.gz
  - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH

script:
  - mkdir output
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/wcag.git output
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/wcag/master/guidelines/index.html -o output/guidelines/22/index.html -f  --retry 3
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/wcag/master/requirements/22/index.html -o output/requirements/22/index.html -f  --retry 3
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/wcag/master/conformance-challenges/index.html -o output/conformance-challenges/index.html -f  --retry 3
  - ant deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: output
  on:
    branch: master
