language: node_js
env:
  global:
    - GH_REF: github.com/w3c/wcag21.git
    
git:
  depth: 3
  
branches:
  only:
    master

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"
  
script:
  - cd ../..
  - mkdir gh-pages
  - cd gh-pages
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/wcag21.git
  - cd wcag21
  - cp -r ../../w3c/wcag21/css css
  - cp ../../w3c/wcag21/guidelines/guidelines.css guidelines/guidelines.css
  - cp ../../w3c/wcag21/guidelines/relative-luminance.xml guidelines/relative-luminance.xml 
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/wcag21/master/requirements/index.html -o requirements/index.html -f --retry 3
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/wcag21/master/guidelines/index.html -o guidelines/index.html -f --retry 3
  - cp ../../w3c/wcag21/understanding/understanding.css understanding/understanding.css
  - cp -r ../../w3c/wcag21/understanding/21 understanding/21 
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/wcag21/master/understanding/index.html -o understanding/index.html -f --retry 3

after_success:
  - git add -A .
  - git commit -m "Generated by TRAVIS-CI"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages > /dev/null 2>&1
