language: node_js
env:
  global:
    - GH_REF: github.com/w3c/wcag.git
    
git:
  depth: 3
  
branches:
  only:
    master

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"
  
script:
  - cd ../..
  - mkdir gh-pages
  - cd gh-pages
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/wcag.git
  - cd wcag
  - mkdir guidelines/22
  - mkdir requirements/22
  - cp -r ../../w3c/wcag/css css
  - cp ../../w3c/wcag/guidelines/guidelines.css guidelines/22/guidelines.css
  - cp ../../w3c/wcag/guidelines/relative-luminance.xml guidelines/22/relative-luminance.xml 
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/wcag/master/requirements/index.html -o requirements/22/index.html -f --retry 3
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/wcag/master/guidelines/index.html -o guidelines/22/index.html -f --retry 3

after_success:
  - git add -A .
  - git commit -m "Generated by TRAVIS-CI"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages > /dev/null 2>&1
