language: java
env:
  global:
    - GH_REF: github.com/w3c/wcag.git
    
git:
  depth: 3
  
script:
  - mkdir output
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/wcag.git output
  - ant deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: output
  on:
    branch: master
