language: java
env:
  global:
    - GH_REF: github.com/w3c/wcag.git
    
git:
  depth: 3
  
branches:
  only:
    master

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"
  
script:
  - ant deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: GH_TOKEN
  keep-history: true
  local-dir: output
  on:
    branch: master
